=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5.json-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "type": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "spec_version": {
            "type": "string"
        },
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "object_marking_refs": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "type": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "identity_class": {
                        "type": "string"
                    },
                    "modified": {
                        "type": "string"
                    },
                    "created": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "created",
                    "id",
                    "identity_class",
                    "modified",
                    "name",
                    "object_marking_refs",
                    "type"
                ]
            }
        }
    },
    "required": [
        "id",
        "objects",
        "spec_version",
        "type"
    ]
}

=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5.json
{
    "type": "bundle",
    "id": "bundle--0ae1557a-3365-4824-bb00-0f192ffdda22",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "type": "identity",
            "id": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "identity_class": "organization",
            "modified": "2017-06-01T00:00:00.000Z",
            "created": "2017-06-01T00:00:00.000Z",
            "name": "The MITRE Corporation"
        }
    ]
}
