=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/malware--0ba9281c-93fa-4b29-8e9e-7ef918c7b13a.json-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "type": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "spec_version": {
            "type": "string"
        },
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "object_marking_refs": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "type": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "x_mitre_aliases": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "x_mitre_version": {
                        "type": "string"
                    },
                    "modified": {
                        "type": "string"
                    },
                    "created": {
                        "type": "string"
                    },
                    "x_mitre_platforms": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "id": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "labels": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "created_by_ref": {
                        "type": "string"
                    },
                    "external_references": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "url": {
                                    "type": "string"
                                },
                                "external_id": {
                                    "type": "string"
                                },
                                "source_name": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "source_name"
                            ]
                        }
                    }
                },
                "required": [
                    "created",
                    "created_by_ref",
                    "description",
                    "external_references",
                    "id",
                    "labels",
                    "modified",
                    "name",
                    "object_marking_refs",
                    "type",
                    "x_mitre_aliases",
                    "x_mitre_platforms",
                    "x_mitre_version"
                ]
            }
        }
    },
    "required": [
        "id",
        "objects",
        "spec_version",
        "type"
    ]
}

=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/malware--0ba9281c-93fa-4b29-8e9e-7ef918c7b13a.json
{
    "type": "bundle",
    "id": "bundle--9cd76699-3009-4e8c-b318-da5a77239106",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "type": "malware",
            "name": "SharpStage",
            "x_mitre_aliases": [
                "SharpStage"
            ],
            "x_mitre_version": "1.1",
            "modified": "2021-08-18T23:48:44.783Z",
            "created": "2020-12-22T17:02:52.954Z",
            "x_mitre_platforms": [
                "Windows"
            ],
            "id": "malware--0ba9281c-93fa-4b29-8e9e-7ef918c7b13a",
            "description": "[SharpStage](https://attack.mitre.org/software/S0546) is a .NET malware with backdoor capabilities.(Citation: Cybereason Molerats Dec 2020)(Citation: BleepingComputer Molerats Dec 2020)",
            "labels": [
                "malware"
            ],
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "external_references": [
                {
                    "url": "https://attack.mitre.org/software/S0546",
                    "external_id": "S0546",
                    "source_name": "mitre-attack"
                },
                {
                    "description": "(Citation: Cybereason Molerats Dec 2020)(Citation: BleepingComputer Molerats Dec 2020)",
                    "source_name": "SharpStage"
                },
                {
                    "url": "https://www.cybereason.com/hubfs/dam/collateral/reports/Molerats-in-the-Cloud-New-Malware-Arsenal-Abuses-Cloud-Platforms-in-Middle-East-Espionage-Campaign.pdf",
                    "description": "Cybereason Nocturnus Team. (2020, December 9). MOLERATS IN THE CLOUD: New Malware Arsenal Abuses Cloud Platforms in Middle East Espionage Campaign. Retrieved December 22, 2020.",
                    "source_name": "Cybereason Molerats Dec 2020"
                },
                {
                    "url": "https://www.bleepingcomputer.com/news/security/hacking-group-s-new-malware-abuses-google-and-facebook-services/",
                    "description": "Ilascu, I. (2020, December 14). Hacking group\u2019s new malware abuses Google and Facebook services. Retrieved December 28, 2020.",
                    "source_name": "BleepingComputer Molerats Dec 2020"
                }
            ]
        }
    ]
}

=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/tool--03c6e0ea-96d3-4b23-9afb-05055663cf4b.json
{
    "type": "bundle",
    "id": "bundle--4e19536a-627f-4bee-a8b6-ea595915b650",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "tool",
            "modified": "2021-04-25T23:30:38.375Z",
            "name": "RemoteUtilities",
            "x_mitre_aliases": [
                "RemoteUtilities"
            ],
            "x_mitre_version": "1.0",
            "created": "2021-03-18T14:57:34.628Z",
            "x_mitre_platforms": [
                "Windows"
            ],
            "id": "tool--03c6e0ea-96d3-4b23-9afb-05055663cf4b",
            "description": "[RemoteUtilities](https://attack.mitre.org/software/S0592) is a legitimate remote administration tool that has been used by [MuddyWater](https://attack.mitre.org/groups/G0069) since at least 2021 for execution on target machines.(Citation: Trend Micro Muddy Water March 2021)",
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "labels": [
                "tool"
            ],
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "external_references": [
                {
                    "url": "https://attack.mitre.org/software/S0592",
                    "external_id": "S0592",
                    "source_name": "mitre-attack"
                },
                {
                    "url": "https://www.trendmicro.com/en_us/research/21/c/earth-vetala---muddywater-continues-to-target-organizations-in-t.html",
                    "description": "Peretz, A. and Theck, E. (2021, March 5). Earth Vetala \u2013 MuddyWater Continues to Target Organizations in the Middle East. Retrieved March 18, 2021.",
                    "source_name": "Trend Micro Muddy Water March 2021"
                }
            ]
        }
    ]
}
