=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/relationship--0a3dbe33-465a-421e-82ca-573d2ca25691.json-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "type": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "spec_version": {
            "type": "string"
        },
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "object_marking_refs": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "type": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "target_ref": {
                        "type": "string"
                    },
                    "modified": {
                        "type": "string"
                    },
                    "source_ref": {
                        "type": "string"
                    },
                    "created_by_ref": {
                        "type": "string"
                    },
                    "relationship_type": {
                        "type": "string"
                    },
                    "created": {
                        "type": "string"
                    },
                    "external_references": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "url": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                },
                                "source_name": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "description",
                                "source_name",
                                "url"
                            ]
                        }
                    }
                },
                "required": [
                    "created",
                    "created_by_ref",
                    "description",
                    "external_references",
                    "id",
                    "modified",
                    "object_marking_refs",
                    "relationship_type",
                    "source_ref",
                    "target_ref",
                    "type"
                ]
            }
        }
    },
    "required": [
        "id",
        "objects",
        "spec_version",
        "type"
    ]
}

=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/relationship--0a3dbe33-465a-421e-82ca-573d2ca25691.json
{
    "type": "bundle",
    "id": "bundle--10321c02-5808-492e-a1e2-8ff4a7308dcb",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "type": "relationship",
            "id": "relationship--0a3dbe33-465a-421e-82ca-573d2ca25691",
            "description": "(Citation: NCC Group Chimera January 2021)",
            "target_ref": "tool--ff6caf67-ea1f-4895-b80e-4bb0fc31c6db",
            "modified": "2021-01-22T16:19:53.855Z",
            "source_ref": "intrusion-set--8c1f0187-0826-4320-bddc-5f326cfcfe2c",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "relationship_type": "uses",
            "created": "2021-01-22T16:19:53.855Z",
            "external_references": [
                {
                    "url": "https://research.nccgroup.com/2021/01/12/abusing-cloud-services-to-fly-under-the-radar/",
                    "description": "Jansen, W . (2021, January 12). Abusing cloud services to fly under the radar. Retrieved January 19, 2021.",
                    "source_name": "NCC Group Chimera January 2021"
                }
            ]
        }
    ]
}
