=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/x-mitre-data-component--2e521444-7295-4dec-96c1-7595b2df7811.json-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "type": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "spec_version": {
            "type": "string"
        },
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "object_marking_refs": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "modified": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "x_mitre_version": {
                        "type": "string"
                    },
                    "x_mitre_data_source_ref": {
                        "type": "string"
                    },
                    "created_by_ref": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "created": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "created",
                    "created_by_ref",
                    "description",
                    "id",
                    "modified",
                    "name",
                    "object_marking_refs",
                    "type",
                    "x_mitre_data_source_ref",
                    "x_mitre_version"
                ]
            }
        }
    },
    "required": [
        "id",
        "objects",
        "spec_version",
        "type"
    ]
}

=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/x-mitre-data-component--2e521444-7295-4dec-96c1-7595b2df7811.json
{
    "type": "bundle",
    "id": "bundle--f89d8233-e34f-4754-9873-9989d1ba1b35",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2021-10-20T15:05:19.275511Z",
            "id": "x-mitre-data-component--2e521444-7295-4dec-96c1-7595b2df7811",
            "description": "Queried domain name system (DNS) registry data highlighting current domain to IP address resolutions (ex: dig/nslookup queries)",
            "x_mitre_version": "1.0",
            "x_mitre_data_source_ref": "x-mitre-data-source--dd75f457-8dc0-4a24-9ae5-4b61c33af866",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "name": "Active DNS",
            "created": "2021-10-20T15:05:19.275511Z",
            "type": "x-mitre-data-component"
        }
    ]
}
