=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/x-mitre-data-source--3bef4799-906c-409c-ac00-3fb7a1e352e6.json-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "type": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "spec_version": {
            "type": "string"
        },
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "object_marking_refs": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "modified": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "x_mitre_version": {
                        "type": "string"
                    },
                    "created_by_ref": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "x_mitre_platforms": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "id": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "x_mitre_collection_layers": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "x_mitre_contributors": {
                        "type": "array"
                    },
                    "created": {
                        "type": "string"
                    },
                    "external_references": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "url": {
                                    "type": "string"
                                },
                                "external_id": {
                                    "type": "string"
                                },
                                "source_name": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "external_id",
                                "source_name",
                                "url"
                            ]
                        }
                    }
                },
                "required": [
                    "created",
                    "created_by_ref",
                    "description",
                    "external_references",
                    "id",
                    "modified",
                    "name",
                    "object_marking_refs",
                    "type",
                    "x_mitre_collection_layers",
                    "x_mitre_contributors",
                    "x_mitre_platforms",
                    "x_mitre_version"
                ]
            }
        }
    },
    "required": [
        "id",
        "objects",
        "spec_version",
        "type"
    ]
}

=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/x-mitre-data-source--3bef4799-906c-409c-ac00-3fb7a1e352e6.json
{
    "type": "bundle",
    "id": "bundle--0402d57c-4eb7-4929-a810-50b8059c1257",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2021-10-20T15:05:19.273623Z",
            "name": "Persona",
            "x_mitre_version": "1.0",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "type": "x-mitre-data-source",
            "x_mitre_platforms": [
                "PRE"
            ],
            "id": "x-mitre-data-source--3bef4799-906c-409c-ac00-3fb7a1e352e6",
            "description": "A malicious online profile representing a user commonly used by adversaries to social engineer or otherwise target victims",
            "x_mitre_collection_layers": [
                "OSINT"
            ],
            "x_mitre_contributors": [],
            "created": "2021-10-20T15:05:19.273623Z",
            "external_references": [
                {
                    "url": "https://attack.mitre.org/datasources/DS0021",
                    "external_id": "DS0021",
                    "source_name": "mitre-attack"
                }
            ]
        }
    ]
}
