=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/x-mitre-tactic--7141578b-e50b-4dcc-bfa4-08a8dd689e9e.json-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "type": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "spec_version": {
            "type": "string"
        },
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "object_marking_refs": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "type": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "x_mitre_shortname": {
                        "type": "string"
                    },
                    "modified": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "created": {
                        "type": "string"
                    },
                    "created_by_ref": {
                        "type": "string"
                    },
                    "external_references": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "source_name": {
                                    "type": "string"
                                },
                                "external_id": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "external_id",
                                "source_name",
                                "url"
                            ]
                        }
                    }
                },
                "required": [
                    "created",
                    "created_by_ref",
                    "description",
                    "external_references",
                    "id",
                    "modified",
                    "name",
                    "object_marking_refs",
                    "type",
                    "x_mitre_shortname"
                ]
            }
        }
    },
    "required": [
        "id",
        "objects",
        "spec_version",
        "type"
    ]
}

=== whitfieldsdad/json-kit/examples/mitre-attack-enterprise/x-mitre-tactic--7141578b-e50b-4dcc-bfa4-08a8dd689e9e.json
{
    "type": "bundle",
    "id": "bundle--eebad39e-2169-4b00-a37a-a155dcbf8e63",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "type": "x-mitre-tactic",
            "name": "Lateral Movement",
            "description": "The adversary is trying to move through your environment.\n\nLateral Movement consists of techniques that adversaries use to enter and control remote systems on a network. Following through on their primary objective often requires exploring the network to find their target and subsequently gaining access to it. Reaching their objective often involves pivoting through multiple systems and accounts to gain. Adversaries might install their own remote access tools to accomplish Lateral Movement or use legitimate credentials with native network and operating system tools, which may be stealthier. ",
            "x_mitre_shortname": "lateral-movement",
            "modified": "2019-07-19T17:44:36.953Z",
            "id": "x-mitre-tactic--7141578b-e50b-4dcc-bfa4-08a8dd689e9e",
            "created": "2018-10-17T00:14:20.652Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "external_references": [
                {
                    "source_name": "mitre-attack",
                    "external_id": "TA0008",
                    "url": "https://attack.mitre.org/tactics/TA0008"
                }
            ]
        }
    ]
}
