=== whitfieldsdad/json-kit/resources/example-data/json/stix2/mitre-capec/json-schema/identity.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "created": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "identity_class": {
            "type": "string"
        },
        "modified": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "object_marking_refs": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "spec_version": {
            "type": "string"
        },
        "type": {
            "type": "string"
        }
    },
    "required": [
        "created",
        "id",
        "identity_class",
        "modified",
        "name",
        "object_marking_refs",
        "spec_version",
        "type"
    ]
}

=== whitfieldsdad/json-kit/examples/stix2/mitre-capec/identity--e50ab59c-5c4f-4d40-bf6a-d58418d89bcd.json
{
    "created": "2023-01-30T20:40:28.791901Z",
    "id": "identity--e50ab59c-5c4f-4d40-bf6a-d58418d89bcd",
    "identity_class": "organization",
    "modified": "2023-01-30T20:40:28.791901Z",
    "name": "The MITRE Corporation",
    "object_marking_refs": [
        "marking-definition--17d82bb2-eeeb-4898-bda5-3ddbcd2b799d"
    ],
    "spec_version": "2.1",
    "type": "identity"
}
